### ISSUE TITLE
handling branch protection rules for new branches

### ISSUE THREAD

**Issue by mattsb42** [mattsb42/repo-admin#16]
One of the sharp edges that I have found in doing the initial setup of projects with Probot-settings is getting the branch protection rules set up for all branches. The root of this is because GitHub will only create branch protection rules for branches that already exist. Combine this with settings configuration only being applied on pushes to the default branch, and it can be laggy and sometimes difficult to get all branches initially set up.

One possible solution to this would be for `repo-admin` to automatically create the branch name specified in the config, using the default branch as a base. This feels a bit too magic to me, but would provide consistent behavior with no user configuration required.

Another option would be to just change what triggers the `repo-admin` workflow. With Probot-settings, we're limited to only triggering on pushes to the default branch, but `repo-admin` runs in a GitHub Actions workflow. You can have it trigger whenever you want!

Following this later option, one pattern that could work is: instead of triggering on master and checking out the current branch:

```yaml
# This workflow applies repository settings once they land in master.
name: Apply repository settings

on:
    push:
        branches:
            - master

jobs:
    apply-settings:
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v2
            -   uses: mattsb42/repo-admin@master
                with:
                    github-token: ${{ secrets.ADMIN_TOKEN }}
                    debug: true
```

you could instead trigger on pushes to master *and* any branch creation and explicitly check out master:

```yaml
# This workflow applies repository settings once they land in master.
name: Apply repository settings

on:
    push:
        branches:
            - master
    create

jobs:
    apply-settings:
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v2
                 with:
                     ref: master
            -   uses: mattsb42/repo-admin@master
                with:
                    github-token: ${{ secrets.ADMIN_TOKEN }}
                    debug: true

```
